### ISSUE TITLE
Repo cleanup?

### ISSUE THREAD

**Issue by smurfix** [guillaume-rico/PrusaLinkPy#2]
Hi,

please

* don't check in dist/ or similar build artefact dictionaries
* tag your release(s)

Thank you.

**Comment by guillaume-rico** [comment]
Hi,
   Glad to see another person using the lib!

I don't understand your first point.
For the second point: I will try to add a tag to future versions.

**Comment by smurfix** [comment]
Sorry. Directories, not dictionaries. Like "dist/" in this case.

**Comment by guillaume-rico** [comment]
Done
